#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
"""Derive the preprocessing configFile schema from the loculus source PPX pins.

PPX runs one preprocessing pipeline -- the nextclade one -- so its configFile shape is
known exactly: it is whatever `Config`, `Segment` and `Reference` declare in
`preprocessing/nextclade/src/loculus_preprocessing/config.py`. Anything else in the
configFile is dropped, because pydantic ignores unknown fields.

The schema is read out of the source with `ast` rather than by importing it: importing
would pull in pydantic and the whole preprocessing dependency tree, and all that is
actually needed is the field names and annotations.

Regenerate whenever `pathoplexus_app/values.yaml`'s `loculusVersion` changes:

    uv run scripts/pipeline-versions/generate_schema.py --loculus ../loculus

CI does this against the checkout it already makes for the helm step, and fails if the
committed schema no longer matches -- so the schema cannot silently drift from the
pipeline actually being deployed.
"""

import argparse
import ast
import json
import re
import subprocess
import sys
from pathlib import Path

CONFIG_PY = "preprocessing/nextclade/src/loculus_preprocessing/config.py"
MODELS = ("Config", "Segment", "Reference")
HERE = Path(__file__).parent
SCHEMA_PATH = HERE / "preprocessing-config-schema.json"

# Annotations we can check a YAML value against. Anything else (enums, nested models,
# tuples) is recorded as null and only its *name* is validated -- better silent than
# wrong.
SIMPLE = {"str": "str", "int": "int", "bool": "bool", "float": "float"}


def _kind(annotation: str) -> str | None:
    a = annotation.replace(" | None", "").strip()
    if a in SIMPLE:
        return SIMPLE[a]
    if a.startswith("list["):
        return "list"
    if a.startswith("dict["):
        return "dict"
    return None


def extract(source: str) -> dict[str, dict[str, str | None]]:
    tree = ast.parse(source)
    out: dict[str, dict[str, str | None]] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name in MODELS:
            out[node.name] = {
                st.target.id: _kind(ast.unparse(st.annotation))
                for st in node.body
                if isinstance(st, ast.AnnAssign)
                and isinstance(st.target, ast.Name)
                and not st.target.id.startswith("_")
            }
    missing = set(MODELS) - set(out)
    if missing:
        sys.exit(f"could not find model(s) {sorted(missing)} in {CONFIG_PY}")
    return out


def pinned_version(repo: Path) -> str:
    text = (repo / "pathoplexus_app" / "values.yaml").read_text()
    m = re.search(r"^loculusVersion:\s*(\S+)", text, re.MULTILINE)
    if not m:
        sys.exit("could not read loculusVersion from pathoplexus_app/values.yaml")
    return m.group(1).strip('"')


def build(loculus: Path, version: str) -> dict:
    source = subprocess.run(
        ["git", "-C", str(loculus), "show", f"{version}:{CONFIG_PY}"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return {
        "_comment": "Generated by generate_schema.py -- do not hand-edit.",
        "loculusVersion": version,
        "source": CONFIG_PY,
        "models": extract(source),
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--loculus", type=Path, required=True, help="path to a loculus checkout")
    p.add_argument("--repo", type=Path, default=HERE.parents[1], help="path to the pathoplexus repo")
    p.add_argument("--check", action="store_true", help="exit 1 if the committed schema is stale")
    args = p.parse_args(argv)

    schema = build(args.loculus, pinned_version(args.repo))
    rendered = json.dumps(schema, indent=2, sort_keys=True) + "\n"

    if args.check:
        current = SCHEMA_PATH.read_text() if SCHEMA_PATH.exists() else ""
        if current != rendered:
            print(
                f"{SCHEMA_PATH.name} is stale for loculusVersion "
                f"{schema['loculusVersion']}. Regenerate it:\n"
                f"  uv run {Path(__file__).name} --loculus <loculus checkout>",
                file=sys.stderr,
            )
            return 1
        print(f"{SCHEMA_PATH.name} is current for loculusVersion {schema['loculusVersion']}")
        return 0

    SCHEMA_PATH.write_text(rendered)
    counts = ", ".join(f"{m} {len(f)}" for m, f in schema["models"].items())
    print(f"wrote {SCHEMA_PATH} from loculusVersion {schema['loculusVersion']} ({counts} fields)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
