name: Create PR to bump main pathoplexus's Loculus version to latest
on:
  workflow_dispatch:
jobs:
  update-loculus-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone Loculus repository and get latest SHA
        id: get_loculus_commit
        run: |
          git clone https://github.com/loculus-project/loculus.git loculus_repo
          cd loculus_repo
          LATEST_SHA=$(git rev-parse HEAD)
          echo "LATEST_SHA=$LATEST_SHA" >> $GITHUB_OUTPUT

      - name: Get current Loculus version
        id: get_current_version
        run: |
          CURRENT_VERSION=$(yq e '.loculusVersion' pathoplexus_app/values.yaml)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Update values.yaml
        run: |
          yq e -i '.loculusVersion = "${{ steps.get_loculus_commit.outputs.LATEST_SHA }}"' pathoplexus_app/values.yaml

      - name: Generate changelog
        id: changelog
        run: |
          cd loculus_repo
          CHANGELOG=$(git log --pretty=format:"- %s" ${{ steps.get_current_version.outputs.CURRENT_VERSION }}..${{ steps.get_loculus_commit.outputs.LATEST_SHA }})
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Loculus version to ${{ steps.get_loculus_commit.outputs.LATEST_SHA }}"
          title: "Update Loculus version to ${{ steps.get_loculus_commit.outputs.LATEST_SHA }}"
          body: |
            ${{ github.actor }} wants to update the Loculus version from ${{ steps.get_current_version.outputs.CURRENT_VERSION }} to ${{ steps.get_loculus_commit.outputs.LATEST_SHA }}.

            ### Changelog:
            ${{ steps.changelog.outputs.CHANGELOG }}

            ### Comparison:
            https://github.com/loculus/loculus/compare/${{ steps.get_current_version.outputs.CURRENT_VERSION }}...${{ steps.get_loculus_commit.outputs.LATEST_SHA }}
          branch: update-loculus-${{ steps.get_loculus_commit.outputs.LATEST_SHA }}
          base: main