name: New Sequences Notification
on:
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./notifications
    steps:
      - uses: actions/checkout@v4
      - name: Set up micromamba environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: notifications/environment.yml
          cache-environment: true
      - name: Run notification script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_SLACK_WEBHOOK_URL }}
        run: python new_releases.py
