name: website

on:
  push:
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ghcr.io/pathoplexus/website

jobs:

  dockerImage:
    name: Build Website Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: read
    steps:
      - uses: actions/checkout@v5
      - run: ./sync.sh
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: dockerMetadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=commit-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./monorepo/website
          push: true
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          cache-from: type=gha,scope=website-${{ github.ref }}
          cache-to: type=gha,mode=max,scope=website-${{ github.ref }}
